#!/usr/bin/env bash

printf "// generated by vega-style-to-dart.sh. Please do not modify this file.\n\nconst String  VegaEmbedStyle = '''\n" > ../lib/src/vega-related-css.dart
sass vega-embed.scss >> ../lib/src/vega-related-css.dart
printf "''';\n\n" >> ../lib/src/vega-related-css.dart
echo "const String  VegaToolTipStyle = '''" >> ../lib/src/vega-related-css.dart
sass vega-tool-tip.scss >> ../lib/src/vega-related-css.dart
printf "''';\n\n" >> ../lib/src/vega-related-css.dart