include: package:pedantic/analysis_options.1.9.0.yaml


analyzer:
  exclude:    
    - 'lib/src/web_view/*.g.dart'
    - 'lib/src/web_view/*.freezed.dart'

linter:
  rules:
    - public_member_api_docs