name: vega_embed_flutter
description:
  A Flutter widget to embed vega-lite charts to flutter web. Works well in Flutter web. 
  An experimental webview based widget is also exposed which can be used in mobile[WIP].

version: 0.7.0-null-safety

homepage: https://github.com/Abhilash-Chandran/vega_embed_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.3
  webview_flutter: ^2.0.4
  freezed_annotation: ^0.14.1
  pedantic: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1+3
  json_serializable: ^4.1.1
  build_runner:  

flutter:
