name: vega_embed_flutter
description:
  A Flutter widget to embed vega-lite charts to flutter web. Works only in Flutter web as of now. This could be adapted
  to be used with flutter webview widget.
version: 0.6.2

homepage: https://github.com/Abhilash-Chandran/vega_embed_flutter

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.0
  webview_flutter: ^0.3.20+2
  freezed_annotation: ^0.11.0
  pedantic: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.11.2
  json_serializable: ^3.3.0
  build_runner:  

flutter:
