on: push
name: build and test
jobs:
  build:
    name: Build vega_embed_flutter on stable
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
            
  publish:
    name: Publish vega_embed_flutter to pub.dev
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish if new
        id: publish
        uses: k-paxian/dart-package-publisher@master
        with:
          flutter: true
          skipTests: true
          accessToken: ${{ secrets.GAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.GAUTH_REFRESH_TOKEN }}
          suppressBuildRunner: true

      - name: Tag commit
        if: steps.publish.outputs.success
        uses: hole19/git-tag-action@master
        env:
          TAG: ${{steps.publish.outputs.package}}-${{steps.publish.outputs.localVersion}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     